### ISSUE TITLE
Crash on 1.20

### ISSUE THREAD

**Issue by sternschnaube** [TISUnion/Carpet-TIS-Addition#105]
### Bug description

Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zfi000$carpet$modifiedRunLoop(MinecraftServer.java:10942) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "hitResult" is null
	at net.minecraft.class_1665.localvar$dim000$puzzleslib$tick$0(class_1665.java:1236) ~[server-intermediary.jar:?]
	at net.minecraft.class_1665.method_5773(class_1665.java:226) ~[server-intermediary.jar:?]
	at net.minecraft.class_1667.method_5773(class_1667.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.redirect$cai000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:7361) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 6 more

### Steps to reproduce

/

### Minecraft version

1.20

### Carpet TIS Addition version

1.48.0

### Fabric Carpet version

1.4.112+v230608

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by sternschnaube** [comment]
I think it's connected to PuzzlesLib and not Carpet TIS.
Sorry.

**Comment by venaminecraft** [comment]
I think it's connected to PuzzlesLib and not Carpet TIS.
Sorry.
