### ISSUE TITLE
Incompatibility between FabricCarpet 1.4.25 and Carpet-TIS?

### ISSUE THREAD

**Issue by Heitzenberg** [TISUnion/Carpet-TIS-Addition#14]
I get the following error while starting up the server:

[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitPositive(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitNegative(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitNegative(I)I with priority 1000
[17:52:52] [main/WARN]: @ModifyConstant conflict. Skipping carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000, already redirected by carpet-tis-addition.mixins.json:rule.structureBlockLimit.StructureBlockBlockEntityMixin->@ModifyConstant::structureBlockLimitNegative(I)I with priority 1000
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
... 7 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at net.minecraft.class_2246.(class_2246.java:835)
at net.minecraft.class_3523.(class_3523.java:13)
at net.minecraft.class_5471.(class_5471.java:11)
at net.minecraft.class_5458.method_30573(class_5458.java:44)
at net.minecraft.class_5458.method_30566(class_5458.java:75)
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at net.minecraft.class_5458.(class_5458.java:74)
at net.minecraft.class_2378.(class_2378.java:237)
at net.minecraft.class_2966.method_12851(class_2966.java:42)
at net.minecraft.server.Main.main(Main.java:87)
... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method positiveLimit(I)I in carpet.mixins.json:StructureBlockBlockEntity_limitsMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
... 30 more

**Comment by QPCrummer** [comment]
Same here. It is because both mods rewrite part of the structure block code now.

**Comment by James103** [comment]
The rule `structureBlockLimit` will need to be removed from Carpet-TIS as it has been merged into the main Carpet mod.

**Comment by shenjackyuanjie** [comment]
所以应该关闭一边的功能能改掉嘛？

**Comment by Fallen-Breath** [comment]
A temporary "fix" is deleting all `rule.structureBlockLimit.xxxxx` in `carpet-tis-addition.mixins.json` in carpet-tis-addition.jar, including:

- `rule.structureBlockLimit.StructureBlockBlockEntityMixin`
- `rule.structureBlockLimit.UpdateStructureBlockC2SPacketMixin`

This should at least, make it runnable with fabric carpet 1.4.25 for now, although the structure block rules might have undefined behavior, but it should be fine if you dont use them

**Comment by Fallen-Breath** [comment]
Won't fix until gnembon/fabric-carpet#712 is resolved, then I will port back a proper fabric carpet structure thing protocol to <=1.15.2 and remove the structureBlockLimit rule in 1.16.4+ TIS addon version

**Comment by srnyx** [comment]
> Won't fix until [gnembon/fabric-carpet#712](https://github.com/gnembon/fabric-carpet/issues/712) is resolved, then I will port back a proper fabric carpet structure thing protocol to <=1.15.2 and remove the structureBlockLimit rule in 1.16.4+ TIS addon version

They fixed [gnembon/fabric-carpet#712](https://github.com/gnembon/fabric-carpet/issues/712)

**Comment by Fallen-Breath** [comment]
Fixed in v1.13.0
