### ISSUE TITLE
在1.20.1中添加此mod无法使用

### ISSUE THREAD

**Issue by YuDeity** [TISUnion/Carpet-TIS-Addition#168]
### Bug description

您好！
我在1.20.1服务端中使用了
carpet 1.4.112+v230608
carpet-tis-addition 1.62.0

但是开机后出现问题
[MCSMANAGER] [INFO] 正在准备启动实例...
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:40:51] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[14:40:51] [ForkJoinPool-1-worker-2/WARN]: Mod gca uses the version mc1.20.1-2.8.0+build.43 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:40:52] [main/WARN]: Mod resolution failed
[14:40:52] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE carpet-tis-addition 1.62.0 {depends fabricloader @ [>=0.14.25]}, ROOT_FORCELOAD_SINGLE carpet-tis-addition 1.62.0]
[14:40:52] [main/INFO]: Reason: [HARD_DEP carpet-tis-addition 1.62.0 {depends fabricloader @ [>=0.14.25]}, HARD_DEP mixinextras 0.3.6 {depends fabricloader @ [>=0.14.25]}, HARD_DEP fabric-api 0.92.2+1.20.1 {depends fabricloader @ [>=0.15.6]}, HARD_DEP fabric-entity-events-v1 1.6.0+1c78457f77 {depends fabricloader @ [>=0.15.6]}]
[14:40:52] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, malilib, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, masa_gadget_mod, fabric-models-v0, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
[14:40:52] [main/INFO]: Fix: add [], remove [], replace [[fabricloader 0.14.22] -> add:fabricloader 0.15.6 ([[0.15.6,∞)])]
[14:40:52] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Fabric Loader' (fabricloader) 0.14.22 with version 0.15.6 or later.
Unmet dependency listing:
         - Mod 'Carpet TIS Addition' (carpet-tis-addition) 1.62.0 requires version 0.14.25 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
         - Mod 'MixinExtras' (mixinextras) 0.3.6 requires version 0.14.25 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
         - Mod 'Fabric API' (fabric-api) 0.92.2+1.20.1 requires version 0.15.6 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
         - Mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.6.0+1c78457f77 requires version 0.15.6 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]

### Steps to reproduce

1.添加carpet TISaddition和carpet mod
2.尝试启动服务器
3.服务器报错自动关闭

4.删除mod
5.服务器启动成功

### Expected behavior

添加mod后成功启动服务器

### Actual behavior

添加mod后服务器启动失败

### Minecraft version

1.20.1fabric

### Carpet TIS Addition version

carpet-tis-addition-v1.62.0-mc1.20.1

### Fabric Carpet version

1.20-1.4.112+v230608

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
错误日志里已经告诉了你问题所在和解决方案了，请阅读并理解。依赖配置问题，与本 mod 无关

```
[14:40:52] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Replace mod 'Fabric Loader' (fabricloader) 0.14.22 with version 0.15.6 or later.
Unmet dependency listing:
- Mod 'Carpet TIS Addition' (carpet-tis-addition) 1.62.0 requires version 0.14.25 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
- Mod 'MixinExtras' (mixinextras) 0.3.6 requires version 0.14.25 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
- Mod 'Fabric API' (fabric-api) 0.92.2+1.20.1 requires version 0.15.6 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
- Mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.6.0+1c78457f77 requires version 0.15.6 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
```

**Comment by YuDeity** [comment]
很抱歉打扰到您了，我巡查了多种结果然未解决，我也是一个新手玩家
