### ISSUE TITLE
Incompatibility with Lithium

### ISSUE THREAD

**Issue by 4rm4g3dd0n** [TISUnion/Carpet-TIS-Addition#183]
### Bug description

Lithium [released ](https://modrinth.com/mod/lithium/version/mc1.21.3-0.14.2) a 1.21.3 version today and TIS Addition requires a specific  Litihum version. 
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Carpet TIS Addition' (carpet-tis-addition) 1.64.2 with any version that is compatible with:
		 - lithium 0.14.2-snapshot+mc1.21.3-build.91
More details:
	 - Mod 'Carpet TIS Addition' (carpet-tis-addition) 1.64.2 is incompatible with any version before 0.13.0 or version 0.14.0- or later of mod 'Lithium' (lithium), but a matching version is present: 0.14.2-snapshot+mc1.21.3-build.91!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

### Steps to reproduce

Run Minecraft with Carpet TIS Addition v1.64.2 for mc1.21.3 and Lithium 0.14.2 for Fabric

### Actual behavior

Game crashes

### Minecraft version

1.21.3

### Carpet TIS Addition version

1.64.2

### Fabric Carpet version

1.21.2-1.4.158+v241022

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
duplicated with #178 #181
