### ISSUE TITLE
game crash when using log projectiles

### ISSUE THREAD

**Issue by Henry8218** [TISUnion/Carpet-TIS-Addition#84]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-11-17 10:32:55
Description: Ticking entity

java.lang.ClassCastException: class [Lnet.minecraft.class_2561; cannot be cast to class [Lnet.minecraft.class_5250; ([Lnet.minecraft.class_2561; and [Lnet.minecraft.class_5250; are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @80503)
	at carpet.logging.logHelpers.TrajectoryLogHelper.handler$znm000$projectileLoggerEnhance(TrajectoryLogHelper.java:603)
	at carpet.logging.logHelpers.TrajectoryLogHelper.lambda$onFinish$0(TrajectoryLogHelper.java:70)
	at carpet.logging.Logger.log(Logger.java:166)
	at carpet.logging.logHelpers.TrajectoryLogHelper.onFinish(TrajectoryLogHelper.java:41)
	at net.minecraft.class_1682.method_5650(class_1682.java:540)
	at net.minecraft.class_1297.method_31472(class_1297.java:373)
	at net.minecraft.class_1680.method_7488(class_1680.java:67)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.minecraft.class_1680.method_5773(class_1680.java:548)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zcb000$modifiedRunLoop(MinecraftServer.java:2885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at carpet.logging.logHelpers.TrajectoryLogHelper.handler$znm000$projectileLoggerEnhance(TrajectoryLogHelper.java:603)
	at carpet.logging.logHelpers.TrajectoryLogHelper.lambda$onFinish$0(TrajectoryLogHelper.java:70)
	at carpet.logging.Logger.log(Logger.java:166)
	at carpet.logging.logHelpers.TrajectoryLogHelper.onFinish(TrajectoryLogHelper.java:41)
	at net.minecraft.class_1682.method_5650(class_1682.java:540)
	at net.minecraft.class_1297.method_31472(class_1297.java:373)
	at net.minecraft.class_1680.method_7488(class_1680.java:67)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.minecraft.class_1680.method_5773(class_1680.java:548)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:snowball (net.minecraft.class_1680)
	Entity ID: 168
	Entity Name: 雪球
	Entity's Exact location: -8.61, -61.98, -6.14
	Entity's Block location: World: (-9,-62,-7), Section: (at 7,2,9 in -1,-4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: -0.00, -1.16, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zcb000$modifiedRunLoop(MinecraftServer.java:2885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['HenryYu2003'/1, l='ServerLevel[珍珠炮]', x=-8.50, y=-63.00, z=-7.05]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-63,0), Section: (at 0,1,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5621 game time, 5621 day time
	Level name: 珍珠炮
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 147643 (now: false), thunder time: 152839 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zcb000$modifiedRunLoop(MinecraftServer.java:2885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 4645100872 bytes (4429 MiB) / 5888802816 bytes (5616 MiB) up to 6392119296 bytes (6096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce MX330
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d16
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1329
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9b41
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1692
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 47878.83
	Virtual memory used (MB): 24722.83
	Swap memory total (MB): 31744.00
	Swap memory used (MB): 1308.91
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx6090m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		appleskin: AppleSkin 2.4.1+mc1.19
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
		badpackets: Bad Packets 0.2.0
		bedrockminer: Bedrock Miner 1.0.0
		carpet: Carpet Mod 1.4.83
		carpet-extra: Carpet Extra 1.4.83
		carpet-tis-addition: Carpet TIS Addition 1.41.1
			conditional-mixin: conditional mixin 0.3.1
			org_yaml_snakeyaml: snakeyaml 1.30
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		continuity: Continuity 2.0.1+1.19
		creativecore: CreativeCore (Fabric) 2.8.5
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		held-item-info: Held Item Info 1.3.0
		indium: Indium 1.0.9+mc1.19.2
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.8.2
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemphysiclite: ItemPhysic Lite (Fabric) 1.5.1
		itemscroller: Item Scroller 0.17.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		libipn: libIPN 1.0.3
		litematica: Litematica 0.12.5
		lithium: Lithium 0.10.0
		magiclib: MagicLib 0.5.37
			magiclib-1_19_2: MagicLib for 1.19.2 0.5.37
		malilib: MaLiLib 0.13.0
		masa_gadget_mod: Masa Gadget 3.0.0-beta+0d38417
			masa_gadget_mod-1_19_2: Masa Gadget for 1.19.2 3.0.0-beta+0d38417
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.0.6
		pca: Plusls carpet addition mod 0.2.5-beta+827168a
			multiconnect-api: MultiConnect API 1.5.10
		phosphor: Phosphor 0.8.1
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		tweakermore: TweakerMore 3.7.1
		tweakeroo: Tweakeroo 0.14.3
		voxelmap: Voxelmap 1.19.2-1.11.10
		wthit: wthit 5.13.3
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['HenryYu2003'/1, l='ServerLevel[珍珠炮]', x=-8.50, y=-63.00, z=-7.05]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.10-1.19.2
#@!@# Game crashed! Crash report saved to: #@!@# D:\BaiduNetdiskDownload\minecraft\.minecraft\versions\fabric-loader-0.14.10-1.19.2\crash-reports\crash-2022-11-17_10.32.55-server.txt
Saving all world maps[10:32:55] [Server thread/INFO]: HenryYu2003 lost connection: 连接中断
[10:32:55] [Server thread/INFO]: HenryYu2003退出了游戏

**Comment by Henry8218** [comment]
It seems that this problem is caused by this carpet extension, instead of carpet itself.

**Comment by Fallen-Breath** [comment]
Should be fixed in dev branch (be2e4887d81330e7a71eade91cdf5c81e12124d8). You can try to use the built mods from github action

**Comment by Fallen-Breath** [comment]
Fixed in release v1.42

**Comment by Henry8218** [comment]
> Fixed in release v1.42
That really works! Thanks very much!
