### ISSUE TITLE
crash with Fabric API 0.41.3+1.16

### ISSUE THREAD

**Issue by raze0727** [TISUnion/Carpet-TIS-Addition#87]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 14/01/2023, 6:00 am
Description: Ticking block entity

java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.api.transfer.v1.item.ItemStorage failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_2614.handler$bom000$hookExtract(class_2614.java:3096)
	at net.minecraft.class_2614.method_11241(class_2614.java:198)
	at net.minecraft.class_2614.method_11249(class_2614.java:109)
	at net.minecraft.class_2614.method_11243(class_2614.java:125)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.redirect$zkl000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3707)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$zbc000$modifiedRunLoop(MinecraftServer.java:2810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet-tis-addition.mixins.json:rule.largeBarrel.compat.fabricapi.ItemStorageMixin from mod carpet-tis-addition] from phase [DEFAULT] in config [carpet-tis-addition.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on TISCM_largeBarrelLookupLogic could not find any targets matching 'lambda$static$2' in net.fabricmc.fabric.api.transfer.v1.item.ItemStorage. Using refmap carpet-tis-addition-mc1.16.5-refmap.json [PREINJECT Applicator Phase -> carpet-tis-addition.mixins.json:rule.largeBarrel.compat.fabricapi.ItemStorageMixin from mod carpet-tis-addition -> Prepare Injections ->  -> handler$bhd000$TISCM_largeBarrelLookupLogic(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2586;Lnet/minecraft/class_2350;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_2614.handler$bom000$hookExtract(class_2614.java:3096)
	at net.minecraft.class_2614.method_11241(class_2614.java:198)
	at net.minecraft.class_2614.method_11249(class_2614.java:109)
	at net.minecraft.class_2614.method_11243(class_2614.java:125)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (10033,118,10020), Chunk: (at 1,7,4 in 627,626; contains blocks 10032,0,10016 to 10047,255,10031), Region: (19,19; contains chunks 608,608 to 639,639, blocks 9728,0,9728 to 10239,255,10239)
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (10033,118,10020), Chunk: (at 1,7,4 in 627,626; contains blocks 10032,0,10016 to 10047,255,10031), Region: (19,19; contains chunks 608,608 to 639,639, blocks 9728,0,9728 to 10239,255,10239)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.redirect$zkl000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3707)

-- Affected level --
Details:
	All players: 1 total; [class_3222['raze0727'/673, l='ServerLevel[void]', x=10032.34, y=117.87, z=10022.39]]
	Chunk stats: ServerChunkCache: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (104,-1,-104), Chunk: (at 8,-1,8 in 6,-7; contains blocks 96,0,-112 to 111,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1344843 game time, 75446 day time
	Level name: void
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 21846 (now: false), thunder time: 28113 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$zbc000$modifiedRunLoop(MinecraftServer.java:2810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2573948416 bytes (2454 MB) / 3221225472 bytes (3072 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms3G -Xmx4G
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		carpet: Carpet Mod 1.4.40
		carpet-autocraftingtable: Auto-Crafting Table mod for carpet-mod 1.4.0
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.43.0
		conditional-mixin: conditional mixin 0.3.2
		fabric: Fabric API 0.41.3+1.16
		fabric-api-base: Fabric API Base 0.3.0+f74f7c7d7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+f74f7c7d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+c16be54b7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+f74f7c7d7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+f74f7c7d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.7+c16be54b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+77df1b337d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+35ff49a47d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+f74f7c7d7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ede6dcf77d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+f74f7c7d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+f74f7c7d7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+9385714e7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4579bd497d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+f74f7c7d7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+f74f7c7d7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+f74f7c7d7d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+c16be54b7d
		fabricloader: Fabric Loader 0.14.12
		fabricproxy-lite: FabricProxy Lite 1.1.3
		ferritecore: FerriteCore 2.1.1
		java: Java HotSpot(TM) 64-Bit Server VM 19
		krypton: Krypton 0.1.2
		lazydfu: LazyDFU 0.1.1
		litematica-server-paster: Litematica Server Paster 1.1.1
		lithium: Lithium 0.6.1
		minecraft: Minecraft 1.16.5
		note-block-chunk-loader: NoteBlock Chunk Loader 1.0.0
		org_yaml_snakeyaml: snakeyaml 1.28
		pca: Plusls carpet addition mod 0.2.5
		phosphor: Phosphor 0.7.2+build.12
		piston-block-chunk-loader: PistonBlock Chunk Loader 1.16.4-1.0.0
		servux: Servux 0.1.6
		syncmatica: Syncmatica 1.16.5-0.3.8
		viabackwards: ViaBackwards 4.0.0
		viafabric: ViaFabric 0.4.1+181-main
		viafabric-mc116: ViaFabric for 1.16 0.4.1+181-main
		viaversion: ViaVersion 4.0.0
		worldedit: WorldEdit 7.2.5+57d5ac9
		xaeroworldmap: Xaero's World Map 1.28.7
	Player Count: 1 / 20; [class_3222['raze0727'/673, l='ServerLevel[void]', x=10032.34, y=117.87, z=10022.39]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Fallen-Breath** [comment]
It's conflicting with fabric api <0.42.0 (actually fabric-transfer-api-v1 <1.5.0). Updating fabric-api should fix this

**Comment by raze0727** [comment]
but it works on my other servers, with the same mods

**Comment by Fallen-Breath** [comment]
> but it works on my other servers, with the same mods

It does crash for me with the same mixin error on the server by placing a hopper. Mod list:

- fabric-carpet-1.16.5-1.4.40+v210608
- carpet-tis-addition-mc1.16.5-v1.43.0
- fabric-api-0.41.3+1.16

Anyway, the fix for the issue is already given in https://github.com/TISUnion/Carpet-TIS-Addition/issues/87#issuecomment-1382816531: update fabric api to >= 0.42.0

**Comment by raze0727** [comment]
now i have this error:
[15:55:27] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.12
[15:55:27] [main/WARN]: Warnings were found!
 - Mod 'ViaBackwards' (viabackwards) 4.0.0 recommends any version of viarewind, which is missing!
	 - You should install any version of viarewind for the optimal experience.
[15:55:27] [main/INFO]: Loading 61 mods:
	- autoconfig1u 3.3.1 via fabricproxy-lite
	- carpet 1.4.40
	- carpet-autocraftingtable 1.4.0
	- carpet-extra 1.4.43
	- carpet-tis-addition 1.43.0
	- conditional-mixin 0.3.2 via carpet-tis-addition
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.12
	- fabricproxy-lite 1.1.3
	- ferritecore 2.1.1
	- java 19
	- krypton 0.1.2
	- lazydfu 0.1.1
	- litematica-server-paster 1.1.1
	- lithium 0.6.1
	- minecraft 1.16.5
	- note-block-chunk-loader 1.0.0
	- org_yaml_snakeyaml 1.28 via viafabric
	- pca 0.2.5
	- phosphor 0.7.2+build.12
	- piston-block-chunk-loader 1.16.4-1.0.0
	- servux 0.1.6
	- syncmatica 1.16.5-0.3.8
	- viabackwards 4.0.0
	- viafabric 0.4.1+181-main
	- viafabric-mc116 0.4.1+181-main via viafabric
	- viaversion 4.0.0 via viafabric
	- xaeroworldmap 1.28.7
[15:55:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/server/Desktop/Survival/server/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[15:55:28] [main/INFO]: Loaded configuration file for Lithium: 66 options available, 1 override(s) found
[15:55:28] [main/ERROR]: Mixin prepare for mod carpet-tis-addition failed preparing translations.StyleAccessor in carpet-tis-addition.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: carpet-tis-addition.mixins.json:translations.StyleAccessor from mod carpet-tis-addition target net.minecraft.class_2583 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: carpet-tis-addition.mixins.json:translations.StyleAccessor from mod carpet-tis-addition target net.minecraft.class_2583 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.1]
[15:55:28] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.1]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	... 1 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet-tis-addition.mixins.json:translations.StyleAccessor from mod carpet-tis-addition] from phase [DEFAULT] in config [carpet-tis-addition.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	... 1 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: carpet-tis-addition.mixins.json:translations.StyleAccessor from mod carpet-tis-addition target net.minecraft.class_2583 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	... 1 more

**Comment by Fallen-Breath** [comment]
> now i have this error:

See #48, fabric proxy is breaking mod compatiblity. It's not related to this issue

**Comment by Fallen-Breath** [comment]
v1.44.1 will introduce better compatibility between fabric api in version range [v0.30.0, v0.42.0)
