### ISSUE TITLE
When running this mod in 1.19.3, the launcher prompts that the injection failed.

### ISSUE THREAD

**Issue by MICOAST** [TISUnion/Carpet-TIS-Addition#88]
## Description

A clear and concise description of what the bug is. It's a Minecraft crash, an unexpected behavior, or something not right.

## To Reproduce

4. ...

What you expect to see: '...'

What actually happens: '...'

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '...'
- Fabric Carpet version: '...'
- Carpet TIS Addition version: '...'
- Other related mod versions: '...'
- ...

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.

**Comment by MICOAST** [comment]
[15:39:31] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[15:39:32] [ForkJoinPool-1-worker-2/WARN]: Mod litematica_printer uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:39:32] [ForkJoinPool-1-worker-4/WARN]: Mod com_github_senseiwells_arucas uses the version d443072775 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'd443072775'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:39:32] [main/INFO]: Loading 140 mods:
	- appleskin 2.4.2+mc1.19.3
	- axolotlitemfix 1.1.4
	- badpackets 0.3.4
	- bedrockminer 2.1
	- betterpingdisplay 1.1.1
	- betterthanmending 1.3.0
	- boostedbrightness 2.1.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- carpet 1.4.93
	- carpet-ams-addition 1.3.5
	- carpet-extra 1.4.91
	- carpet-fixes 1.19.3-1.13.0
	- carpet-tis-addition 1.44.0
	- chat_heads 0.9.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94 via appleskin
	- com_akuleshov7_ktoml-core-jvm 0.3.0 via zoomify
	- com_github_llamalad7_mixinextras 0.1.1 via zoomify
	- com_github_senseiwells_arucas d443072775 via essential-client
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- conditional-mixin 0.3.2 via carpet-tis-addition
	- creativecore 2.9.3
	- customskinloader 14.15.1
	- dev_isxander_settxi_settxi-core 2.10.6 via zoomify
	- dev_isxander_settxi_settxi-gui 2.10.6 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6 via zoomify
	- easiervillagertrading 1.19.3-fabric0.68.1-1.5.4
	- entityculling 1.5.2-mc1.19.3
	- essential-client 1.3.2
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- gbfabrictools 1.3.4+1.19.3 via easiervillagertrading
	- gca 2.4.1-1.19
	- imblocker 1.0.20
	- inventoryhud 3.4.7
	- inventoryprofilesnext 1.9.1
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- iris 1.5.1
	- itemphysic 1.6.7
	- itemscroller 0.18.0
	- java 17
	- kyrptconfig 1.5.1-1.19.3 via quickshulker
	- libipn 2.0.1
	- litematica 0.13.1
	- litematica_printer ${version}
	- magiclib 0.6.200+a47eb26-beta
	- magiclib-1_19_3 0.6.200+a47eb26-beta via magiclib
	- malilib 0.14.0
	- masa_gadget_mod 3.0.0-beta+f5856ee
	- masa_gadget_mod-1_19_3 3.0.0-beta+f5856ee via masa_gadget_mod
	- minecraft 1.19.3
	- minihud 0.25.0
	- modmenu 5.0.2
	- nochatreports 1.19.3-v1.19.0
	- ommc 0.5-beta+20ce4cc
	- ommc-1_19_3 0.5-beta+20ce4cc via ommc
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- pearltickets 1.19.2-1.1.4
	- phosphor 0.8.1
	- quickshulker 1.3.10-1.19.3
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- replaymod 1.19.3-2.6.10
	- settxi-gui-yacl 2.10.6 via zoomify
	- shulkerutils 1.0.4-1.19 via quickshulker
	- skinlayers 1.5.2-mc1.19.3
	- smoothswapping 0.6.1
	- sodium 0.4.8+build.22
	- sodium-extra 0.4.16+mc1.19.3-build.91
	- syncmatica 1.18.2-0.3.8
	- tweakermore 3.9.2
	- tweakeroo 0.15.0
	- tweakmyclient 3.4.303+867af56-beta
	- tweakmyclient-1_19_3 3.4.303+867af56-beta via tweakmyclient
	- wthit 6.1.2
	- xaerominimap 22.17.0
	- xaeroworldmap 1.28.7
	- yet-another-config-lib 2.2.0
	- zoomify 2.9.2
[15:39:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/Minecraft%20PCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:39:33] [main/INFO]: Compatibility level set to JAVA_17
[15:39:34] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[15:39:35] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[15:39:35] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 1 override(s) found
[15:39:36] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[15:39:39] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[15:39:41] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[15:39:41] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[15:39:41] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[15:39:41] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[15:39:48] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[15:39:48] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[15:39:50] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[15:39:50] [main/ERROR]: Mixin apply for mod carpet-tis-addition failed carpet-tis-addition.mixins.json:command.lifetime.deathdamage.ItemEntityMixin from mod carpet-tis-addition -> net.minecraft.class_1542: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1542::onDeathLifeTimeTracker with priority 1000 cannot inject into net/minecraft/class_1542::method_5643(Lnet/minecraft/class_1282;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet-tis-addition.mixins.json:command.lifetime.deathdamage.ItemEntityMixin from mod carpet-tis-addition -> Prepare Injections ->  -> handler$caa001$onDeathLifeTimeTracker(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1542::onDeathLifeTimeTracker with priority 1000 cannot inject into net/minecraft/class_1542::method_5643(Lnet/minecraft/class_1282;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet-tis-addition.mixins.json:command.lifetime.deathdamage.ItemEntityMixin from mod carpet-tis-addition -> Prepare Injections ->  -> handler$caa001$onDeathLifeTimeTracker(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[SCC客户端.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[SCC客户端.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[15:39:50] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1542 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1542 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[SCC客户端.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[SCC客户端.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[SCC客户端.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[SCC客户端.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet-tis-addition.mixins.json:command.lifetime.deathdamage.ItemEntityMixin from mod carpet-tis-addition] from phase [DEFAULT] in config [carpet-tis-addition.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[SCC客户端.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[SCC客户端.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1542::onDeathLifeTimeTracker with priority 1000 cannot inject into net/minecraft/class_1542::method_5643(Lnet/minecraft/class_1282;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> carpet-tis-addition.mixins.json:command.lifetime.deathdamage.ItemEntityMixin from mod carpet-tis-addition -> Prepare Injections ->  -> handler$caa001$onDeathLifeTimeTracker(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[SCC客户端.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[SCC客户端.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 8 more

**Comment by Fallen-Breath** [comment]
Seems like it's conflicting with mod `itemphysic`

**Comment by Fallen-Breath** [comment]
ItemPhysic overwrites a method in `ItemEntity` completely, which breaks mod compatibility hard

https://github.com/CreativeMD/ItemPhysic/blob/e6224837590d309b9921015515316fb44322887c/src/main/java/team/creative/itemphysic/mixin/ItemEntityMixin.java#L73-L79

**Comment by MICOAST** [comment]
> ItemPhysic overwrites a method in `ItemEntity` completely, which breaks mod compatibility hard
> 
> https://github.com/CreativeMD/ItemPhysic/blob/e6224837590d309b9921015515316fb44322887c/src/main/java/team/creative/itemphysic/mixin/ItemEntityMixin.java#L73-L79

Okay,it is solven,thanks very much
